//Compile-time error:
//Syntax error:
// console.log);

//Runtime-error:
//Reference Error:
// console.log(x);

// try {
//   console.log("I am inside try block and try block starts here");
//   console.log(x);
//   console.log("Try block ends here");
// } catch (err) {
//   console.log("I am inside catch block");
//   console.log("Throw err: ", err);
// } finally {
//   console.log("I will run everytime, no matter what as i am finally block.");
// }

// console.log("k")

//Custom error:

// try{
//     console.log(x);
// }
// catch(err)
// {
//     throw new Error("Bhai pehle declare karo fer print karna");
// }
